config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "users#index"

  devise_for :users
  resources :stories, only: [:new, :create, :show, :edit, :update]
  resources :users, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :user
  has_many_attached :images
  has_many_attached :videos
  has_rich_text :description

  validates :title, :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  has_many :stories

  validates :nickname, :address, presence: true

  geocoded_by :address
  after_validation :geocode

  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode

  after_create :update_city

  scope :artists, -> { where(artist: true) }

  def update_city
    town = Geocoder.search address

    update(city: town[0].data['address']['city']) unless town.nil?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || users_path
  end

  def after_update_path_for(resource)
    stored_location_for(resource) || user_path(current_user)
  end

	protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, 
    :nickname, :latitude, :longitude, :avatar, :artist, :address])
    devise_parameter_sanitizer.permit(:account_update, keys: [:last_name, :first_name, 
    :nickname, :latitude, :longitude, :avatar, :artist, :address, :city])
  end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create]
	before_action :find_story, only: [:show, :edit, :update]

	def new
		@story = Story.new
	end

	def create
		@story = current_user.stories.new(story_params)

		if @story.save
			redirect_to story_path(@story)
		else
			render "new"
		end
	end

	def show ;end

	def edit ;end

	def update
		byebug

		if @story.update(story_params)
			redirect_to story_path(@story)
		else
			render :edit
		end
	end

	private

	def find_story
		@story = Story.find(params[:id])
	end

	def story_params
		params.require(:story).permit(:title, :description, :user_id, :images, :videos)
	end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	include ActiveStorage::SetCurrent
	before_action :find_user, only: [:show]

	def index
		@users = User.artists
	end

	def show; end

	private

	def find_user
		@user = User.includes(:stories).find(params[:id])
	end

	def user_params
		params.require(:user).permit(:last_name, :first_name, :nickname, :latitude,
    :longitude, :avatar, :artist, :address)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stories_helper.rb
module StoriesHelper

	def form_story_url(story)
		if story.new_record?
			stories_path
		else
			story_path(story)
		end
	end

	def story_title_form(story)
		if story.new_record?
			content_tag(:div, class: 'title mb-3') do
				content_tag(:h2, 'Nouvelle histoire')
			end
		else
			content_tag(:div, class: 'title mb-3') do
				content_tag(:h2, 'Edite ton histoire')
			end			
		end
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TemporaireWebsite
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application.bootstrap", "data-turbo-track": "reload"
    = javascript_importmap_tags "application"
  %body
    = render(NavbarComponent.new(navbar: 'Music Story Beta'))
    .container-fluid.overflow-hidden
      = yield

app/views/stories/edit.haml
.edit-story.mx-auto.mt-4.border.border-light.p-4
	= render(NewEditStoryFormComponent.new(story: @story))

app/views/stories/new.haml
.new-story.mx-auto.mt-4.border.border-light.p-4
	= render(NewEditStoryFormComponent.new(story: @story))

app/views/stories/show.haml
.story.mt-4
	- if user_signed_in? && current_user.artist?
		.edit-button.mb-3.w-50.mx-auto
			= link_to 'Editer mon histoire', edit_story_path(@story), class: 'btn btn-primary btn-lg w-100'
	
	.paper
		%h1.title.text-center
			= @story.title

		.story-descrition.w-50.mx-auto.mt-4
			= @story.description

app/views/users/index.haml
.users
  .users-avatar
    .row
      - @users.each do |user|
        .col-2  
          .avatar.mx-3.my-4.text-center.border.border-light.shadow.hvr-grow.w-100
            = link_to user_path(user.id) do
              - if user.avatar.attached?
                = image_tag(user.avatar, class: 'rounded-circle user-avatar pt-2')
              - else
                %h3 NO image
              %h3.user-info.mt-3
                = user.nickname

app/views/users/show.haml
.story-show
	.row.mt-5
		.col-3.p-4.border-end
			.user-stories.text-center
				- if @user.avatar.attached?
					= image_tag(@user.avatar.url, class: 'rounded-circle user-avatar mt-3')
				- else
					%h1
						NO IMAGE

				%h1.user-info.pt-5
					= @user.nickname

				.edit-button
					= link_to 'Editer mon profile', edit_user_registration_path, class: 'btn btn-primary btn-lg w-100'

		.col-9
			.stories.text-center.mt-5
				#accordionFlushExample.accordion.accordion-flush
					- @user.stories.each_with_index do |story, i|
						.accordion-item
							%h2{id: "flush-headingOne#{i}", class: "accordion-header"}
								%button.accordion-button.collapsed{"aria-controls" => "flush-collapse#{i}", "aria-expanded" => "false", "data-bs-target" => "#flush-collapse#{i}", "data-bs-toggle" => "collapse", type: "button"}
									= story.title

							%div{id: "flush-collapse#{i}", class: "accordion-collapse collapse", "aria-labelledby" => "flush-heading#{i}", "data-bs-parent" => "#accordionFlushExample"}
								.accordion-body
									= link_to story_path(story.id) do
										= story.description.body.to_plain_text.truncate(200)